import tempfile
import unittest
from pathlib import Path

from a2a_cli.main import (
    _extract_findings_from_agent_output,
    _validate_cover_changelog_quality,
    _validate_patchset_artifact_coherence,
    _validate_respin_delta,
)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


class PostRespinValidationTests(unittest.TestCase):
    def test_extract_findings_from_noisy_output(self) -> None:
        noisy = (
            "progress line\n"
            '{"findings":[{"severity":"low","title":"x","location":"a.patch:1","evidence":["e"],'
            '"required_action":"none","status":"closed","source_comment_id":"id-1"}]}\n'
            "tail"
        )
        findings = _extract_findings_from_agent_output(noisy)
        self.assertIsInstance(findings, list)
        self.assertEqual(len(findings or []), 1)

    def test_patchset_artifact_coherence_detects_subject_total_mismatch(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "out"
            patch_dir = out / "demo.patches"
            _write(
                patch_dir / "0000-cover-letter.patch",
                "Subject: [PATCH v3 0/2] demo\n\n---\n",
            )
            _write(
                patch_dir / "0001-a.patch",
                "Subject: [PATCH v3 1/2] a\n\n---\ndiff --git a/a.c b/a.c\n",
            )
            _write(
                patch_dir / "0002-b.patch",
                "Subject: [PATCH v3 2/3] b\n\n---\ndiff --git a/b.c b/b.c\n",
            )
            _write(
                patch_dir / "series",
                "0000-cover-letter.patch\n0001-a.patch\n0002-b.patch\n",
            )
            _write(out / "demo.cover", "Subject: [PATCH v3 0/2] demo\n")
            _write(
                out / "demo.mbx",
                "Subject: [PATCH v3 1/2] a\n\n---\n\nSubject: [PATCH v3 2/2] b\n",
            )

            issues = _validate_patchset_artifact_coherence(out)
            self.assertTrue(any("0002-b.patch" in issue for issue in issues))

    def test_patchset_artifact_coherence_accepts_mbx_with_cover_row(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "out"
            patch_dir = out / "demo.patches"
            _write(
                patch_dir / "0000-cover-letter.patch",
                "Subject: [PATCH v3 0/2] demo\n\n---\n",
            )
            _write(
                patch_dir / "0001-a.patch",
                "Subject: [PATCH v3 1/2] a\n\n---\ndiff --git a/a.c b/a.c\n",
            )
            _write(
                patch_dir / "0002-b.patch",
                "Subject: [PATCH v3 2/2] b\n\n---\ndiff --git a/b.c b/b.c\n",
            )
            _write(
                patch_dir / "series",
                "0000-cover-letter.patch\n0001-a.patch\n0002-b.patch\n",
            )
            _write(out / "demo.cover", "Subject: [PATCH v3 0/2] demo\n")
            _write(
                out / "demo.mbx",
                "\n".join(
                    [
                        "Subject: [PATCH v3 0/2] demo",
                        "",
                        "Subject: [PATCH v3 1/2] a",
                        "",
                        "Subject: [PATCH v3 2/2] b",
                        "",
                    ]
                ),
            )

            issues = _validate_patchset_artifact_coherence(out)
            self.assertEqual([], issues)

    def test_cover_changelog_quality_detects_tool_meta_text(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "out"
            _write(
                out / "0000-cover-letter.patch",
                "\n".join(
                    [
                        "Subject: [PATCH v3 0/1] demo",
                        "",
                        "---",
                        "Changes since v2:",
                        "- Automated respin update generated by A2A.",
                        "",
                    ]
                )
                + "\n",
            )
            issues = _validate_cover_changelog_quality(out)
            self.assertTrue(any("non-technical/tool-meta" in issue for issue in issues))

    def test_respin_delta_detects_touched_file_drift(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            src = root / "src"
            out = root / "out"
            _write(
                src / "0001-a.patch",
                "Subject: [PATCH v2 1/1] demo\n\n---\ndiff --git a/a.c b/a.c\n",
            )
            _write(
                out / "0001-a.patch",
                "Subject: [PATCH v3 1/1] demo\n\n---\ndiff --git a/b.c b/b.c\n",
            )
            issues = _validate_respin_delta(src, out)
            self.assertTrue(any("touched-file drift" in issue for issue in issues))


if __name__ == "__main__":
    unittest.main()
